name: cli
description: A demo for creating a CLI tool with Dart.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dcli: ^7.0.3
  http: ^1.4.0
  path: ^1.9.1
  crypto: ^3.0.6 #加密
  archive: ^3.6.1 # 解压
  pubspec_parse: ">=1.3.0 <2.0.0" #解析 pubspec.yaml 文件
  args: ^2.7.0 #命令行参数
  image: ^4.3.0
  pool: ^1.5.1 #线程池

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  cli: cli

# Include templates in the package
include:
  - lib/templates/page/
